markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: ""

version: 1.0.0

github:
  repo: https://github.com/marsbergen/styleguide

sass:
  sass_dir: css
